### ISSUE TITLE
옵션에 대한 구상.

### ISSUE THREAD

**Issue by khw7096** [coldmine/ic#1]
옵션에 대한 구상.
- input / -i
- output / -o
- width / -w
- height / -h
- gamma / -g

**Comment by khw7096** [comment]
- 정비율로 줄어들것.
- width만 적으면 height는 자동으로 계산될것.

**Comment by kybin** [comment]
> width만 적으면 height는 자동으로 계산될것.

또는 그 반대.

**Comment by khw7096** [comment]
Fixed 600ef30
