### ISSUE TITLE
cmd 디렉토리를 유지해야 할까요?

### ISSUE THREAD

**Issue by kybin** [coldmine/ic#4]
생각보다 두 디렉토리를 왔다갔다 하는게 불편하네요.

지금은 합쳤다가 ic가 추후 커지면 분리하는것도 하나의 방법일것 같아요.

**Comment by khw7096** [comment]
일단 전 아직은 보류..^^;; 전 이동에 아직 관대해요.

**Comment by kybin** [comment]
오케이.

**Comment by khw7096** [comment]
나중에 메인경로에 많은 파일이 실제로 생길거라공 예측이되기도 해서 추후 분리할 것이라면 아직은.. 그대로 두자라는 생각도 있구요.

**Comment by kybin** [comment]
그래요. 저는 상대적으로 파일이 적지 않을까라고 생각했는데, 한웅씨 생각이 그렇다면 그냥 디렉토리구조를 가지는게 더 좋을것 같아요~

2016년 10월 16일 오후 10:57, hanwoong kim notifications@github.com님이 작성:
