### ISSUE TITLE
// TODO: Support multiple kernels 의미

### ISSUE THREAD

**Issue by kybin** [coldmine/ic#6]
golang.org/x/image/draw에는 몇가지 필터 방식이 있어요. 

그걸 커널이라고도 부르더라구요. 사용자가 필터 방식을 변경할수 있어야 되기 때문에 쓴 말이에요. 

아래는 해당 코드 레퍼런스에요.

https://github.com/golang/image/blob/master/draw/scale.go#L154

**Comment by khw7096** [comment]
Good
