### ISSUE TITLE
Resize함수가 image를 받고 image를 반환하면 더 좋지 않을까요?

### ISSUE THREAD

**Issue by kybin** [coldmine/ic#7]
현재 Resize함수는 라이브러리스럽지는 않은것 같아요.

**Comment by khw7096** [comment]
저도 https://github.com/nfnt/resize
코드를 보면서 그런생각을 하고 있어요.

**Comment by khw7096** [comment]
image -> image 라면 사실 위 라이브러리를 사용하는게 당연히 좋을것 같고..
개념적 라이브러리말고, 기능적 라이브러리를 만드는것도 가치가 있을것 같고,
방향성을 일단 고민하고 있어요.

**Comment by khw7096** [comment]
기능적 라이브러리의 장점은.. 초보 golang 사용자가 분명 사용하기 쉬울듯하기도 하고..  모 일단 이런저런걸 끄적거려보고 있어요.

**Comment by khw7096** [comment]
장점2. 실제로 내가 사용할 때 코드줄수를 최소화 하는것도 현 코드의 장점.

**Comment by kybin** [comment]
음. 제가 드는 생각은 ic가 라이브러리 보다는 쓰기 편한 명령어라는 관점에서 접근하는게 더 좋을것 같아요. 

우리는 그쪽에 아이디어가 더 많기 때문에..

그렇다고 Resize가 image를 받고 image를 반환해야 한다는 생각에 변함이 있는건 아니에요.

**Comment by kybin** [comment]
그래서 이 주제에 대한 생각은 어때요? 만약 좋다면 제가 구현할게요.

**Comment by khw7096** [comment]
OK

**Comment by kybin** [comment]
c6a9958 에 의해 해결됨.
